### ISSUE TITLE
Demo project not compiling

### ISSUE THREAD

**Issue by ren6** [appodeal/appodeal-ios-demo#1]
I have multiple issues with demo project
At first, your ENUM values are redefined. 
FIX: You should change words used in your AODAppodealAdType enum.
![2015-06-24 22 06 13](https://cloud.githubusercontent.com/assets/1678575/8339073/a5e6aafa-1abd-11e5-93dd-ff81b041a4be.jpg)

At second it says: Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'Main'. 
FIX: You should add Main.storyboard to target membership.

**Comment by dmitruss** [comment]
comment for start on iOS simulator
// NONE       = 0,

FIX: You should add Main.storyboard to target membership. 
DONE
