### ISSUE TITLE
Appodeal Crashes on initializeWithApiKey

### ISSUE THREAD

**Issue by appleguy1999** [appodeal/appodeal-ios-demo#11]
Within my app when I attempt to initialize Appodeal with 
```
[Appodeal initializeWithApiKey:[[NSBundle mainBundle] objectForInfoDictionaryKey:@"AppodealAppKey"] types:AppodealAdTypeAll]
```
I get the following crash log
```
2015-09-22 17:39:49.080 frameTest[1414:373737] +[NSValueTransformer appodeal_numberAsStringTransformer]: unrecognized selector sent to class 0x3ada8790
2015-09-22 17:39:49.081 frameTest[1414:373737] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSValueTransformer appodeal_numberAsStringTransformer]: unrecognized selector sent to class 0x3ada8790'
```
I am using Appodeal SDK Version 0.4.8 with Objective C and this occurs on both the simulator and on actual devices

**Comment by ploddi** [comment]
You should specify `-ObjC` flag in `Other linker flags`.

**Comment by appleguy1999** [comment]
```-ObjC``` has been specified in ```Other linker flags```. When that linker flag is included I get
```ld: 1191 duplicate symbols for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)```

Most of the duplicate symbols appear to be GoogleMobileAds related

**Comment by ploddi** [comment]
This is probably bitcode related. You should use XCode 7 with SDK version 0.4.9 or higher, or try to downgrade to 0.4.8.

**Comment by appleguy1999** [comment]
This error is coming up in Xcode Version 7.0 (Build: 7A220) with bitcode disabled. When I run ```AppodealApiVersionString()```, it says that I am already running version 0.4.8. and I have not seen where to download version 0.4.9 outside of CoccoaPods (which this project does not use) because the official [Change Log](http://www.appodeal.com/sdk/changelog) still lists 0.4.8 as the most recent version.

**Comment by dmitruss** [comment]
0.4.9 version will be available since 25.09.2015

**Comment by appleguy1999** [comment]
Oh, ok. Thank you!

**Comment by terenzeyuen** [comment]
Im having the same issue with the latest SDK version. Any advice?
