### ISSUE TITLE
Callback Not Getting Called

### ISSUE THREAD

**Issue by neutt22** [appodeal/appodeal-ios-demo#13]
I just signed up yesterday and ran into problems where callbacks for Interstitial is not getting called. 
So I asked for help from Appodeal online support guys. They are great, quick response, etc. but they can't seem to fix this problem. 

At first I tried to load a test interstitial without callback with simple:

`while(!Appodeal.isLoaded(Appodeal.INTERSTITIAL)){
			yield return null;
			Debug.Log("waiting for ads");
		}
		Debug.Log("waiting is done, showing ads");`

But no interstitial ads is showing up on my Unity editor. (btw, this is for Android)

So one guy recommended me to use callbacks. So I implemented the `IInterstialAdListener` with simple `Debug.Log` statements in it to see if it's working. Unfortunately, the guy still not getting back at me regarding my issue.

Unity 5 Editor
Windows 10 32bit
Android only

Thanks!

**Comment by A1NE** [comment]
Hi! Please send apk with problem (nk@appodeal.com). 
Also, you are trying to run it on emulator or real device?

**Comment by neutt22** [comment]
Hi,

Noted on sending the APK with ads issue.

Both. Both don't work on Unity Editor/real dev.

Thanks

**Comment by A1NE** [comment]
SDK not working with Unity Editor. Only on Android devices or emulators (like Genymotion). 
Can you send bigger piece of code, where you are calling ads to show?
Also check AppodealDEMO.cs, maybe it will help to understand where is the problem.

If you will send me apk, i'll see what kind of problem there.

Thanks.

**Comment by neutt22** [comment]
Maybe it should be stated in the docs that the SDK is not working yet on Unity. 

Anyway, here's the codes for Appodeal itself:

      using UnityEngine;
      using System.Collections;
      using UnityEngine.UI;

     using AppodealAds.Unity.Api;
     using AppodealAds.Unity.Common;

    public class AdsManager : MonoBehaviour, IInterstitialAdListener {

	public void onInterstitialLoaded() { Appodeal.show (Appodeal.INTERSTITIAL); }
	public void onInterstitialFailedToLoad() { print("Interstitial failed"); }
	public void onInterstitialShown() { print("Interstitial opened"); }
	public void onInterstitialClosed() { print("Interstitial closed"); }
	public void onInterstitialClicked() { print("Interstitial clicked"); }


	void Start () {
		Appodeal.setInterstitialCallbacks(this);
		Appodeal.initialize("587522c7d976e33e7a0afd87f7d63a2497e6a062566b91a1", Appodeal.VIDEO | Appodeal.INTERSTITIAL);
	}
}

`
^ not working, currently uploading APK (20+ MB) 

Also, is there anyway to cut down the size? It puts good amount of MB in the APK size as well :/

Thanks

**Comment by neutt22** [comment]
APK DL link:
https://drive.google.com/open?id=0Bw3pE9ny0VIuZWFvZEpJZVJQQnM

**Comment by A1NE** [comment]
Ok we will add it do docs, sdk works with iOS and Android, Unity Editor Player is just desktop platform, so it can't work there.

Ads shows properly for me on my Nexus 5 in your apk. Genymotion emulator works fine too.
On what devices are you testing it?

**Comment by neutt22** [comment]
My APK works on yours?!! That craaazy. Try to run it on 4.2 (Jelly Bean) because that's my current mobile dev.

Thanks

**Comment by neutt22** [comment]
I'm downloading blue stacks app emulator atm.. hopefully theres a settings to set to 4.2

**Comment by A1NE** [comment]
Tried on Genymotion Android 4.2, works.

**Comment by neutt22** [comment]
Then this is bad IDK what to do now :/ 
Android version is 4.2.1
Cherry Mobile Apollo

I'm not just sure what's happening. That same APK i sent is the one installed now on that device.
Any advice?

**Comment by A1NE** [comment]
Can you send me full logcat after running this app on your phone?

**Comment by neutt22** [comment]
Okay I fixed it now. It's because I didn't know I was using an AdBlocker -__-
But it's saying it's missing coarse perm. Anyway, closing this issue.

Thanks buddy!
