### ISSUE TITLE
Cant compile 0.6 virsion with cocoapods

### ISSUE THREAD

**Issue by Sergionius** [appodeal/appodeal-ios-demo#14]
Have 30 errors 
![2015-11-16 13 57 57](https://cloud.githubusercontent.com/assets/10280032/11180238/3fe7c724-8c6a-11e5-8344-897af5dbfae9.png)

**Comment by dmitruss** [comment]
Demo project was updated.

**Comment by never911** [comment]
Download latest version. Use pod update, have this errors
![2015-11-18 12 06 37](https://cloud.githubusercontent.com/assets/13120232/11236914/b9cdd6c6-8ded-11e5-8e79-d967a14e843d.png)

**Comment by ploddi** [comment]
Try `pod update`.

**Comment by never911** [comment]
@ploddi I try it
