### ISSUE TITLE
Error with AppodealSetRewardedVideoDelegate in last version sdk

### ISSUE THREAD

**Issue by EgorkZe** [appodeal/appodeal-ios-demo#15]
I built unity project to xcode proj and when i build it a got this error:

Undefined symbols for architecture arm64:
  "_AppodealSetRewardedVideoDelegate", referenced from:
      _AppodealObjCBridge_AppodealSetRewardedVideoDelegate_m2532 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _AppodealObjCBridge_AppodealSetRewardedVideoDelegate_m2532)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ploddi** [comment]
Fixed. Please follow documentation to redownload Appodeal Unity Plugin package.
