### ISSUE TITLE
Apps crashes on initializeWithApiKey

### ISSUE THREAD

**Issue by terenzeyuen** [appodeal/appodeal-ios-demo#16]
Ran a build from Unity using the demo scene but crashes as soon as I click Initialize.

Error:
[NSValueTransformer appodeal_numberAsStringTransformer]: unrecognized selector sent to class 0x1a033a9c0

**Comment by ploddi** [comment]
You have to add `-ObjC` flag to `Other Linker Flags` on `Build Settings` tab.

**Comment by terenzeyuen** [comment]
I have tried, assuming we should be adding at Targets but getting this error instead:
![screen shot 2015-11-20 at 11 28 28](https://cloud.githubusercontent.com/assets/2553680/11298852/e44fb2ec-8f79-11e5-9cd4-ecb554344d8a.png)
![screen shot 2015-11-20 at 11 28 52](https://cloud.githubusercontent.com/assets/2553680/11298853/e44ff5a4-8f79-11e5-84c2-8d75383ab283.png)

**Comment by dmitruss** [comment]
Please add framework
JavaScriptCore

**Comment by terenzeyuen** [comment]
Cool it's working now. :+1:

**Comment by terenzeyuen** [comment]
I have just updated to 0.6.2 but having this error now
![screen shot 2015-11-20 at 12 32 50](https://cloud.githubusercontent.com/assets/2553680/11299975/3caa5e70-8f83-11e5-8593-e60c92d033cf.png)
