### ISSUE TITLE
[!] Error installing AppLovin (cocoapods)

### ISSUE THREAD

**Issue by MilaFabio** [appodeal/appodeal-ios-demo#17]
1. cocoapods-0.39.0 
2. pod 'Appodeal', '~> 0.5' # for XCODE 7  or  pod 'Appodeal'

```
[!] Error installing AppLovin
[!] /usr/bin/curl -f -L -o /var/folders/q1/xvsmc82n7tlgstjjn40q5pqc0000gn/T/d20151215-8873-1d1y6vr/file.tbz http://sdk.applovin.com/applovin-ios-sdk-3.1.3.tar.bz2 --create-dirs

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (22) The requested URL returned error: 403 Forbidden
```
How to fix it?

**Comment by ploddi** [comment]
Make sure Appodeal CocoaPods repo appears first in your `Podfile`:
```
source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/CocoaPods/Specs.git'
```

**Comment by MilaFabio** [comment]
I have: 
```
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

source 'git@github.com:CocoaPods/Specs.git'
source 'git@github.com:appodeal/CocoaPods.git'
```
I replaced your code, the error has not changed

**Comment by ploddi** [comment]
Can you provide output of `pod update --verbose` command?

**Comment by ploddi** [comment]
AppLovin podspec updated to 3.2.1. It should updates now.

**Comment by MilaFabio** [comment]
pod update --verbose
...
```

-> Installing AppLovin (3.1.6)
 > Http download
   $ /usr/bin/curl -f -L -o /var/folders/q1/xvsmc82n7tlgstjjn40q5pqc0000gn/T/d20151215-19299-1pd3jdi/file.tbz
   http://sdk.applovin.com/applovin-ios-sdk-3.1.6.tar.bz2 --create-dirs
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (22) The requested URL returned error: 403 Forbidden

[!] Error installing AppLovin
[!] /usr/bin/curl -f -L -o /var/folders/q1/xvsmc82n7tlgstjjn40q5pqc0000gn/T/d20151215-19299-1pd3jdi/file.tbz http://sdk.applovin.com/applovin-ios-sdk-3.1.6.tar.bz2 --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0curl: (22) The requested URL returned error: 403 Forbidden

```

**Comment by MilaFabio** [comment]
Thank you so much! Now it works! You helped me a lot.

**Comment by bb-git** [comment]
So what was the solution? I'm facing the same error.

-> Installing AppLovin (3.1.3)
 > Http download
   $ /usr/bin/curl -f -L -o
   /var/folders/kx/z8_yqlq12s10g164q86bb3s40000gn/T/d20160122-3701-y5yibh/file.tbz
   http://sdk.applovin.com/applovin-ios-sdk-3.1.3.tar.bz2 --create-dirs
     % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                    Dload  Upload   Total   Spent    Left  Speed
     0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 403 Forbidden

**Comment by dmitruss** [comment]
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update

than

platform :ios, '7.1'   
source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/CocoaPods/Specs.git'
pod 'Appodeal', '~> 0.8'
target 'Your App Build Target Name' do
end

**Comment by bb-git** [comment]
I just copied the commands to the console and ran them in the directory of the Podfile. I'm still getting the same error.

There is no SDK at this URL: http://sdk.applovin.com/applovin-ios-sdk-3.1.3.tar.bz2
