### ISSUE TITLE
Undefined symbols for architecture x86_64 for Flurry

### ISSUE THREAD

**Issue by MilaFabio** [appodeal/appodeal-ios-demo#18]
XCODE 7.2
project on Swift
BITCODE=NO
VALID_ARCHS = armv6 armv7 armv7s arm64

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FlurryAdNative", referenced from:
      objc-class-ref in Appodeal(AppodealFurryNativeAdAdapter.o)
  "_OBJC_CLASS_$_FlurryAdTargeting", referenced from:
      objc-class-ref in Appodeal(AppodealFurryNativeAdAdapter.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
how can I fix it?

**Comment by staskochkin** [comment]
Hello, what version of sdk are you use in your project?

**Comment by MilaFabio** [comment]
today only with cocoapods updated to 7.0

**Comment by staskochkin** [comment]
You don't have flurry sdk, try to remove Pods folder and Podfile.lock in your project, and run pod install

**Comment by katsgeorgeek** [comment]
+1 the same problem

**Comment by dmitruss** [comment]
please clear Caches


rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update


actual version of Appodeal CocoaPods - is 0.8.1

**Comment by katsgeorgeek** [comment]
@dmitruss didn't fix for me

**Comment by dmitruss** [comment]
We are planing to support Swift Appodeal Cocoapods integration during 2-3 weeks.
Now you can use Framework integration - 
https://github.com/appodeal/appodeal-ios-demo/tree/master/SwiftAppodealFrameworkDemo

**Comment by Shulepov** [comment]
Also got this error

**Comment by Shulepov** [comment]
Not sure were actually issue is, possibly it's in spec for Flurry itself.
But i was able to solve it by doing this:

- add 'Other linker flags':
```
-l"Flurry_7.3.0"
-l"FlurryAds_7.3.0"
```

- add library search paths:
```
${PODS_ROOT}/Flurry-iOS-SDK/FlurryAds
${PODS_ROOT}/Flurry-iOS-SDK/Flurry
```

**Comment by KoD4K** [comment]
Don't want to make a new issue but have the same problem with inMoby
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IMBanner", referenced from:
      objc-class-ref in Appodeal(AppodealInMobiBannerView.o)
  "_OBJC_CLASS_$_IMInterstitial", referenced from:
      objc-class-ref in Appodeal(AppodealInMobyRewardedVideoAdapter.o)
      objc-class-ref in Appodeal(AppodealInMobiInterstitialAdapter.o)
  "_OBJC_CLASS_$_IMNative", referenced from:
      objc-class-ref in Appodeal(AppodealInMobyNativeAd.o)
      objc-class-ref in Appodeal(AppodealInMobiNativeAdAdapter.o)
  "_OBJC_CLASS_$_IMRequestStatus", referenced from:
      l_OBJC_$_CATEGORY_IMRequestStatus_$_Appodeal in Appodeal(IMError+Appodeal.o)
  "_OBJC_CLASS_$_IMSdk", referenced from:
      objc-class-ref in Appodeal(AppodealInMobyRewardedVideoAdapter.o)
      objc-class-ref in Appodeal(AppodealInMobiInterstitialAdapter.o)
      objc-class-ref in Appodeal(AppodealInMobiBannerView.o)
      objc-class-ref in Appodeal(AppodealInMobiNativeAdAdapter.o)
      objc-class-ref in Appodeal(InMobi+Appodeal.o)
      l_OBJC_$_CATEGORY_IMSdk_$_Appodeal in Appodeal(InMobi+Appodeal.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I have this frameworks from cocoa pods:
```
Using AFNetworking (2.6.3)
Using AdColony (2.6.1)
Using AmazonAds (2.2.11)
Using AppLovin (3.2.1)
Using Appodeal (0.8.1)
Using AppsFlyer-SDK (4.3.7)
Using Avocarrot (3.4.3)
Using Bolts (1.6.0)
Using ChartboostSDK (6.3.0)
Using CocoaLumberjack (2.2.0)
Using Crashlytics (3.6.0)
Using FBAudienceNetwork (4.10.0)
Using FBSDKCoreKit (4.10.0)
Using FBSDKLoginKit (4.10.0)
Using FBSDKShareKit (4.10.0)
Using FMDB (2.6)
Using Fabric (1.6.5)
Using FacebookAdsSDK (4.6.0)
Using Flurry-iOS-SDK (7.3.0)
Using Godzippa (1.1.0)
Using Google-Mobile-Ads-SDK (7.6.0)
Using GoogleAnalytics (3.14.0)
Using HCSStarRatingView (1.4.3)
Using Haneke (1.0.2)
Using InMobiSDK (5.2.0)
Using KSCrash (0.0.9)
Using Mantle (2.0.6)
Using Masonry (0.6.4)
Using MillenialMediaSDK (6.1.0)
Using MyTarget (4.3.0)
Using NexageSourceKitCommon (1.0.3)
Using NexageSourceKitMRAID (1.0.6)
Using NexageSourceKitVAST (1.0.6)
Using Parse (1.12.0)
Using PubNative (1.4.0)
Using RevvForMobile (3.2.0)
Using SVProgressHUD (1.1.3)
Using SpotX-SDK (2.1.1-fix)
Using StartApp (3.3.0)
Using UnityAds (1.5.4)
Using VungleAdvertiserSDK (3.1.2)
Using YandexMobileAds (2.0.1)
Using YandexMobileMetrica (2.3.0)
Using iRate (1.11.4)
Using mopub-ios-sdk (4.3.0)
Using protobuf-c (1.0.1)
```

**Comment by dmitruss** [comment]
Check Podfile please:

platform :ios, '7.1'

source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/CocoaPods/Specs.git'
pod 'Appodeal', '~> 0.8'
target 'Your App Build Target Name' do
end

**Comment by rlam3** [comment]
@KoD4K were you able to find a workaround?
