### ISSUE TITLE
duplicate symbols for architecture arm64 for Flurry

### ISSUE THREAD

**Issue by IvanVorobei** [appodeal/appodeal-ios-demo#20]
Flag -ObjC set
Bitcode = NO
project on Swift
![screen shot 2015-12-18 at 00 40 26](https://cloud.githubusercontent.com/assets/10995774/11882852/1bb7f1d4-a520-11e5-9d4b-3c2e91ccd0f0.png)

**Comment by dmitruss** [comment]
please remove your integration of Flurry.
our SDK contains Flurry inside.
To use it in you project adds .h files (from Flurry) and initialize Flurry with your key.

**Comment by IvanVorobei** [comment]
Thank you! It help for me!
But after ubdate to Appodeal 7.0 I have much warnings
>200
![screen shot 2015-12-18 at 00 59 25](https://cloud.githubusercontent.com/assets/10995774/11883241/a5f434fa-a522-11e5-8efb-3625fef684c8.png)

**Comment by dmitruss** [comment]
<img width="659" alt="screen shot 2015-12-18 at 01 12 32" src="https://cloud.githubusercontent.com/assets/1777197/11883566/f15a6660-a524-11e5-9501-5a6dff0f89aa.png">

**Comment by dmitruss** [comment]
improve Xcode Build Option
