### ISSUE TITLE
Ошибка при установке AppLovin через cocoapods

### ISSUE THREAD

**Issue by gritsov** [appodeal/appodeal-ios-demo#21]
> [!] Error installing AppLovin
> [!] /usr/bin/curl -f -L -o /var/folders/22/74b5m5d12j97plykvf5zp4pm0000gn/T/d20160207-21920-mmis8k/file.tbz https://sdk.applovin.com/applovin-ios-sdk-3.2.1.tar.bz2 --create-dirs
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (22) The requested URL returned error: 403 Forbidden

По ссылке https://sdk.applovin.com/applovin-ios-sdk-3.2.1.tar.bz2 ничего нет
Это если ставить демо проект. На другом проекте установилось нормально, но вытекло в такие ошибки: 
> ld: library not found for -lAppLovinSdk
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

и

> ld: library not found for -lFlurryAds_7.3.0
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dmitruss** [comment]
swift?

**Comment by gritsov** [comment]
objective-c

**Comment by ploddi** [comment]
`Podfile.lock` закомичен в нем залочена версия `AppLovin 3.2.1`, а они периодически удаляют архивы со старыми версиями.

Следует выполнить `pod update` вместо `pod install`.

**Comment by gritsov** [comment]
я пробовал, ни то, ни другое не работает

**Comment by KoD4K** [comment]
Мне помогло 
pod 'AppLovin', '3.2.1' 
в Podfile

**Comment by dmitruss** [comment]
Check Podfile please: 

platform :ios, '7.1'   
source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/CocoaPods/Specs.git'
pod 'Appodeal', '~> 0.8'
target 'Your App Build Target Name' do
end

**Comment by gritsov** [comment]
ios 7.1 обязательна? если нет, то не работает по-прежнему

**Comment by gritsov** [comment]
Пофиксил ворнинги при установке, сделал pod update и pod install и с конфигурацией из комментария выше всё работает. Всем спасибо, ребят
