### ISSUE TITLE
duplicate symbol for Appodeal(AppodealCircleTimer.o)

### ISSUE THREAD

**Issue by VladimirSharaev** [appodeal/appodeal-ios-demo#22]
Hello, i have some issues. Please help me.
![2016-04-07 10 38 06](https://cloud.githubusercontent.com/assets/13451448/14343942/081014a6-fcad-11e5-9042-6d4e5ea9c7d8.png)
Appodel installed with CocoaPods.
My Podfile:
<img width="610" alt="2016-04-07 10 41 32" src="https://cloud.githubusercontent.com/assets/13451448/14343999/5e9e51a2-fcad-11e5-9132-6d013b923d42.png">

**Comment by ytn3rd** [comment]
Same issue here using Xamarin. I am also using Mixpanel, SDWebImage and Facebook SDKs.

**Comment by dmitruss** [comment]
fixed, please use last version of Appodeal
