### ISSUE TITLE
symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by prizrak1609** [appodeal/appodeal-ios-demo#24]
XCODE 7.3.1
project on Swift
BITCODE=NO
VALID_ARCHS = armv7 armv7s arm64

Appodeal added without cocoapods

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CBUUID", referenced from:
      objc-class-ref in Appodeal(flat-arm64)
  "_OBJC_CLASS_$_CBCentralManager", referenced from:
      objc-class-ref in Appodeal(flat-arm64)
  "_CBCentralManagerOptionShowPowerAlertKey", referenced from:
      l936 in Appodeal(flat-arm64)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

how can I fix it?

**Comment by dmitruss** [comment]
please add CoreBluetooth.framework

**Comment by prizrak1609** [comment]
add CoreBluetooth.framework

and now:

duplicate symbol _OBJC_CLASS_$_PodsDummy_Pods in:
    /Users/dimagubatenko/Library/Developer/Xcode/DerivedData/AppPay-fatmwrkfyyuuzwalsoqsryadfxxz/Build/Products/Debug-iphoneos/Pods.framework/Pods(Pods-dummy.o)
    /Users/dimagubatenko/Xcode projects/AppPay/Appodeal.framework/Appodeal(Pods-dummy.o)
duplicate symbol _OBJC_METACLASS_$_PodsDummy_Pods in:
    /Users/dimagubatenko/Library/Developer/Xcode/DerivedData/AppPay-fatmwrkfyyuuzwalsoqsryadfxxz/Build/Products/Debug-iphoneos/Pods.framework/Pods(Pods-dummy.o)
    /Users/dimagubatenko/Xcode projects/AppPay/Appodeal.framework/Appodeal(Pods-dummy.o)
ld: 2 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by staskochkin** [comment]
Are you use cocoa pods in your project?

**Comment by prizrak1609** [comment]
yes

**Comment by staskochkin** [comment]
It's possible to integrate Appodeal Sdk via Cocoa Pods?

**Comment by prizrak1609** [comment]
I try but xcode show error "include of non-modular header inside framework module"

**Comment by staskochkin** [comment]
What version of cocoa pods are you use?

**Comment by prizrak1609** [comment]
0.39.0

**Comment by staskochkin** [comment]
What version of Appodeal are you use by cocoa pods?

**Comment by prizrak1609** [comment]
pod 'Appodeal', '~> 0.10'

**Comment by prizrak1609** [comment]
Appodeal 0.10.6

**Comment by prizrak1609** [comment]
error "Include of non-modular header inside framework module 'Appodeal'"
only if i click in Xcode: Product -> Archive

**Comment by prizrak1609** [comment]
when i run this steps, error gone :
1) clean project -> delete derived data -> clean project again
2) remove *.xcworkspace
3) remove Podfile.lock and Pods directory
4) update cocoapods to 1.0.1
5) add target to Podfile
6) run pod install then pod update

Thanks for help)
