### ISSUE TITLE
AFNetwork > 3.0

### ISSUE THREAD

**Issue by coldmint** [appodeal/appodeal-ios-demo#25]
Добрый день. Решил использовать Appodeal через cocoapods, но столкнулся с тем, что в Appodeal стоит AFNetwork 2.6.3, а я уже использую в проекте 3.1.0.
Соотвественно оба я не могу иметь в PodFile, выдает ошибку.
Можно ли как-то совместить эти вещи?

**Comment by staskochkin** [comment]
Добрый день, вы можете использовать толстый клиент Appodeal Sdk для интеграции  в своем проекте: https://bit.ly/21jG1Ks. Так как для работы Appodeal Sdk необходим AFNetwork 2.6.3. А версию 3.1.0. вы можете оставить в Вашем Podfile.

**Comment by coldmint** [comment]
Да, спасибо, так и сделал.
