### ISSUE TITLE
Xcode 8 (Swift 2.3 and Swift 3.0) support

### ISSUE THREAD

**Issue by JohnEstropia** [appodeal/appodeal-ios-demo#28]
Now that Xcode 8 is made public, hopefully the Appodeal iOS SDK starts supporting Swift 2.3 and Swift 3.0 as well

**Comment by dmitruss** [comment]
Hi. Appodeal iOS SDK was updated for iOS 10 support.
Demo project is here - https://github.com/appodeal/appodeal-ios-new-demo
