### ISSUE TITLE
duplicate symbols for architecture arm64 1.3.3 iOS SDK

### ISSUE THREAD

**Issue by alexzhuchinskyi** [appodeal/appodeal-ios-demo#29]
Hello! After updating SDK 1.3.3 I got error "ld: 692 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
" Please help me to solve it.
![screenshot at nov 24 15-12-51](https://cloud.githubusercontent.com/assets/22845605/20599752/81464dde-b258-11e6-87fe-2d7762908cbd.png)

**Comment by staskochkin** [comment]
Hello, are you using CocoaPods integration or manual? Are VungleSdk exist in project?

**Comment by alexzhuchinskyi** [comment]
manual

**Comment by staskochkin** [comment]
And you using VungleSdk in your project?

**Comment by alexzhuchinskyi** [comment]
No, I have investigated all project and not found VingleSDK

**Comment by alexzhuchinskyi** [comment]
Oh, solved! Thank You!  I just  removed "-all_load" from "Other Linker Flags" and all works!
![screenshot at nov 24 16-47-09](https://cloud.githubusercontent.com/assets/22845605/20602377/aa0817d6-b265-11e6-9a5a-885372d7c123.png)

**Comment by alexzhuchinskyi** [comment]
Thank You for fast response. I think that fast response is impossible but You kill thoughts. Thank You!

**Comment by staskochkin** [comment]
I was happy to help, good luck!

**Comment by alexzhuchinskyi** [comment]
When I can download adapters for last iOS SDK ?

**Comment by staskochkin** [comment]
Now adapters include in SDK

**Comment by staskochkin** [comment]
And your version must contain them all if your using http://bit.ly/appodeal-ios-sdk-fat-1-3-3

**Comment by alexzhuchinskyi** [comment]
I got "<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.". Do You know why it happens ?

**Comment by dmitruss** [comment]
It is logs from Admob. Generally it means -  no Fill

**Comment by alexzhuchinskyi** [comment]
Could You write, how long downloading "RewardedVideo" using "showAd:AppodealShowStyleRewardedVideo"?  Because I want to show the video after start the app but this video not showing .

**Comment by dmitruss** [comment]
Please contact with our Support Team via email -  hi@appodeal.com, support@appodeal.com or via Intercom on our site - www.appodeal.com. Thanks.
