### ISSUE TITLE
Appodeal ios demo not working. Needs more instructions. Thanks! 

### ISSUE THREAD

**Issue by rlam3** [appodeal/appodeal-ios-demo#32]
Need instruction on how to run demo. Thanks! 

Wasn't able to get cocoapods working with this repo. Is this outdated? Thanks!

**Comment by staskochkin** [comment]
Hi!
This demo not supports CocoaPods integration. Only manual integration available there. 
You should clone this repo and download latest [Appodeal SDK](http://bit.ly/appodeal-ios-sdk-2-1-10-release). After you should just drag&drop Appodeal.framework and Resources folder into SDK folder in this repo.  That's all.

CocoaPods installation docs available in [Appodeal Docs](https://www.appodeal.com/sdk/documentation?framework=20&full=1&integration=2&platform=4).
