### ISSUE TITLE
disable networks ?

### ISSUE THREAD

**Issue by matrixreal** [appodeal/appodeal-ios-demo#33]
Hello,
i'm using appodeal for banner and interstitial (i don't want to use rewarded video)
and i would like to disable some networks
how can i do it ?
thanks

**Comment by matrixreal** [comment]
i have an app that use only banner and interstitial (video and static)
i want to remove the other rewarded video networks like unity adcolony since they don't offer banner or intersitial ads
the size of the sdk is huge
thank you

**Comment by staskochkin** [comment]
Hello! 
You can use Cocoapods integration and add only subspecies that you need
Interstitial example:
```ruby
target 'Name' do
 pod 'Appodeal/Interstitial', '~> 2.1'
end
```
Single network adapter example:
```ruby
target 'Name' do
pod 'Appodeal/AppLovinAdapter', '2.3.3'
end
```
