### ISSUE TITLE
Assigning APDImage to UIImageView

### ISSUE THREAD

**Issue by CalvinTp** [appodeal/appodeal-ios-demo#36]
I am currently using Appodeal version 2.1.10. I have created my own native tableViewCell manually and wanted to assign the information to the cell. 

I have no issue to assign information such as Title, SubTitle (which are NSString) or Rating (which are NSNumber); however, I have some trouble assigning images such as IconImage.

        logoImageView.image = nativeAd.iconImage;

The code above will cause the following error to be flagged:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[APDImage imageOrientation]: unrecognized selector sent to instance 0x1d04316a0'

How do I manually assign IconImage to an UIImageView?

**Comment by staskochkin** [comment]
@CalvinTp Hello. Crash occurs cause `APDImage` isn't subclass of `UIImage`. 
This class contains property url - `@property (nonatomic, strong, readonly) NSURL * url;`
You need to download (check that url is remote first, for some ad networks it may be local) image and assign it to your `logoImageView`

**Comment by CalvinTp** [comment]
@staskochkin thanks, I can use iconImage.url to download the image. Btw, is there any code sample for version 2.1.10. The demo for 2.1.10 does not contain any example for native ads.
