### ISSUE TITLE
[[Appodeal bannerView] isHidden] is not YES after invoking [Appodeal hideBanner]

### ISSUE THREAD

**Issue by adriano-di-giovanni** [appodeal/appodeal-ios-demo#38]
`[[Appodeal bannerView] isHidden]` is not `YES` after invoking `[Appodeal hideBanner]`.

This happens on `2.4.1-Beta2`.

**Comment by staskochkin** [comment]
Hello, @adriano-di-giovanni
Thanks for you feedback. We will fix it in `2.4.4` version.
