### ISSUE TITLE
Build fails on iOS

### ISSUE THREAD

**Issue by be-bert** [appodeal/appodeal-ios-demo#39]
Here is the error Xcode outputs.

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_WCSession", referenced from:
      objc-class-ref in Appodeal(ADCDevice.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by staskochkin** [comment]
Hello, @be-bert!
Just add `WatchConnectivity` system framework to link binary with libraries build phase of your target.
