### ISSUE TITLE
Is Native ads not available from 2.4.9?

### ISSUE THREAD

**Issue by aboutthismac** [appodeal/appodeal-ios-demo#41]
Hi I am creating native ad's. After version 2.1 It seems buggy in SDK. Following the official documentations are not helping.

I've cloned this repository and Compiled successfully after 30 mins. The native ads not working with this repository too.

Native ads not available from 2.4.9?
[Video.mov.zip](https://github.com/appodeal/appodeal-ios-demo/files/2667853/Video.mov.zip)

**Comment by BoikoArtem30091994** [comment]
Do you found how to fix this issues?

**Comment by BoikoArtem30091994** [comment]
> Hi I am creating native ad's. After version 2.1 It seems buggy in SDK. Following the official documentations are not helping.
> 
> I've cloned this repository and Compiled successfully after 30 mins. The native ads not working with this repository too.
> 
> Native ads not available from 2.4.9?
> [Video.mov.zip](https://github.com/appodeal/appodeal-ios-demo/files/2667853/Video.mov.zip)

Do you found how to fix this issues?

**Comment by aboutthismac** [comment]
Hi BoikoArtem,

I tried several ways to fix.. I contacted Appodeal team. They also don't know how to fix. This is totally wast framework ever I've used. It will eat lot of time without reason.

I simply deleted Appodeal from project. Problem solved!
