### ISSUE TITLE
xcode10 报这个错误

### ISSUE THREAD

**Issue by GameMidlet** [appodeal/appodeal-ios-demo#43]
ld: framework not found Appodeal
clang: error: linker command failed with exit code 1 (use -v to see invocation)

求解决

**Comment by staskochkin** [comment]
Your should download fat Appodeal.framework, and drag&drop it into **SDK** folder of project. Please read [docs](https://wiki.appodeal.com/en/ios/2-5-11-ios-sdk-integration-guide)
