### ISSUE TITLE
Custom banner doesn't show up

### ISSUE THREAD

**Issue by andreyoshev** [appodeal/appodeal-ios-demo#47]
![Simulator Screen Shot - iPhone 11 - 2020-06-17 at 18 24 53](https://user-images.githubusercontent.com/17673010/84903731-e5e21180-b0c7-11ea-8c63-8fb342547f47.png)

Не показывается `custom banner` (`APDBannerView`), `static banner` работает ок: заглушка Appodeal.

Это демо проект, на боевом проекте тоже не работает.

**Comment by staskochkin** [comment]
@andreyoshev Спасибо за фидбек! 
Похоже в последней версии 2.6.4 возникла проблема при интеграции `APDBannerView` через `storyboard`. Мы изучим проблему и включим исправления в следующий релиз. 
Пока Вы можете использовать предыдущую версию Appodeal SDK - 2.6.3 либо добавить `APDBannerView` программно.

**Comment by andreyoshev** [comment]
@staskochkin я его программно и добавляю :) Скриншот с демо проекта.

**Comment by staskochkin** [comment]
@andreyoshev В демке он добавлен в `storyboard`, в коде контроллера передается только `adSize` и [вызов загрузки](https://github.com/appodeal/appodeal-ios-demo/blob/ddb30a439295839cb5614470dd3b38021b2f9c7a/AppodealSwiftDemo/AppodealSwiftDemo/CustomBannerViewController.swift#L38)
Если метод `setup` изменить на 
``` swift
func setup() {
        let bannerView = APDBannerView(size: kAPDAdSize320x50, rootViewController: self)
        bannerView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(bannerView)
        NSLayoutConstraint.activate([
            bannerView.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            bannerView.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            bannerView.heightAnchor.constraint(equalToConstant: kAPDAdSize320x50.height),
            bannerView.widthAnchor.constraint(equalTo: view.widthAnchor),
        ])
        bannerView.loadAd()
}
```
то баннер рендерится, но мы в любом случае рассмотрим эту проблему

**Comment by andreyoshev** [comment]
```
private lazy var bannerView: APDBannerView = APDBannerView(size: iPad ? kAPDAdSize728x90 : kAPDAdSize320x50, rootViewController: self)

        bannerView.usesSmartSizing = true
        bannerView.delegate = self
        bannerView.backgroundColor = .red
        view.addSubview(bannerView)
        
        bannerView.loadAd()

        bannerView.snp.updateConstraints { make in
            make.leading.equalToSuperview()
            make.trailing.equalToSuperview()
            make.bottom.equalToSuperview()
            make.height.equalTo(iPad ? 90 : 50)
        }
```

Вот так добавляю, виден только серый прямоугольник.

**Comment by andreyoshev** [comment]
Норм, если добавлять баннер не во `viewDidLoad`, то срабатывает окей :)
С задержкой тоже работает.

**Comment by staskochkin** [comment]
@andreyoshev Спасибо за комментарий, проверим этот кейс

**Comment by staskochkin** [comment]
@andreyoshev Привет! Мы добавили правки в **2.6.5**. `APDBannerView` должен работать нормально, при условии что метод 
``` swift
Appodeal.initialize(withApiKey: "some key", types: .banner, hasConsent: consent)
```
был вызван до создания инстанса `APDBannerView`
