### ISSUE TITLE
App memory skyrocketing

### ISSUE THREAD

**Issue by jiangyunzhao** [appodeal/appodeal-ios-demo#50]
when i use appodeal , and Add ads to the article list， The memory of my app grows rapidly by more than 100M，most more than 300M, and it drops very slowly, it make my app very lagging。
My test machine is Apple 7p and emulator, both of which exist.
<img width="357" alt="WechatIMG16" src="https://user-images.githubusercontent.com/26105405/138832418-34a1b88e-6e42-4baa-b1d6-4a47320e6c39.png">

**Comment by staskochkin** [comment]
I'll close this task due to inactivity.
