### ISSUE TITLE
Pod crash

### ISSUE THREAD

**Issue by MilaFabio** [appodeal/appodeal-ios-demo#8]
<strong>в Pod файле:</strong>
<code> source 'https://github.com/CocoaPods/Specs.git'</code>
<code> source 'https://github.com/appodeal/CocoaPods.git'</code>
<code> pod 'Appodeal', '~> 0.4.0'</code>
<hr>
<strong>terminal: pod install (или pod update)</strong>
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (2.5.4)
Using AdColony (2.5.2)
Installing AmazonAds 2.2.8 (was 2.2.8)
Installing AppLovinSDK (3.0.2)
Installing Appodeal (0.4.2)
Installing Bugsnag (4.0.7)

<strong>
[!] Error installing Bugsnag
[!] /usr/bin/git submodule update --init

Submodule 'KSCrashModule' (git@github.com:bugsnag/KSCrash.git) registered for path 'KSCrashModule'
Cloning into 'KSCrashModule'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:bugsnag/KSCrash.git' into submodule path 'KSCrashModule' failed
</strong >
<hr>
подскажите как решить эту проблему

**Comment by ploddi** [comment]
Нужно сгенерировать публичный ssh ключ
https://help.github.com/articles/generating-ssh-keys/
