### ISSUE TITLE
Test device and adMob

### ISSUE THREAD

**Issue by MilaFabio** [appodeal/appodeal-ios-demo#9]
1. Как указать что запрос на устройство тестовый, а то уже случайно нажала на банер и мне зачли 0.05$, не хотелось бы чтобы за 5 центов гугл меня  забанил (приложение еще не выложено AppStore).
2. Если аккаунт adMob и Appodeal синхронизированы, когда я выложу приложение в AppStore нужно будет " Установить связь с приложением"?

**Comment by dmitruss** [comment]
1. [Appodeal setDebugEnabled:YES];
2. yes. please sync appstore link with your app in Admob

**Comment by MilaFabio** [comment]
Thanks
